//! Foundation service ownership for the Platform Kernel.

mod analytics;
mod application;
mod application_launch;
mod audit;
mod configuration;
mod context;
mod database;
mod desktop_window;
mod discovery;
mod execution_cancellation;
mod execution_context;
mod execution_guard;
mod execution_outcome;
mod execution_reconciliation;
mod graph;
mod layout;
mod intent_execution;
mod observation;
mod projection;
mod registry;
mod suggestion;
mod suggestion_intent;
mod suggestion_lifecycle;
mod widget;
mod workspace;
mod zone;

pub use analytics::WorkspaceAnalyticsService;
pub use application::ApplicationService;
pub use application_launch::ApplicationLaunchService;
pub use audit::AuditService;
pub use configuration::ConfigurationService;
pub use context::WorkspaceContextService;
pub use database::DatabaseServiceHandle;
pub use desktop_window::DesktopWindowService;
pub use discovery::CapabilityResolver;
pub use execution_cancellation::ExecutionCancellationService;
pub use execution_context::ExecutionContextService;
pub use execution_guard::ExecutionGuardService;
pub use execution_outcome::ExecutionOutcomeService;
pub use execution_reconciliation::ExecutionReconciliationService;
pub use graph::GraphService;
pub use layout::LayoutService;
pub use intent_execution::GovernedIntentExecutionService;
pub use observation::ObservationService;
pub use projection::WorkspaceProjectionService;
pub use registry::{RegisteredService, ServiceRegistry, ServiceStatus};
pub use suggestion::SuggestionService;
pub use suggestion_intent::SuggestionIntentService;
pub use suggestion_lifecycle::SuggestionLifecycleService;
pub use widget::WidgetService;
pub use workspace::WorkspaceService;
pub use zone::ZoneService;
