//! Foundation service ownership for the Platform Kernel.

mod action_catalog;
mod ai_assistant;
mod ai_evaluation;
mod ai_memory;
mod ai_model_provider;
mod ai_orchestration;
mod ai_personalization;
mod ai_participation;
mod ai_planning;
mod analytics;
mod application;
mod application_launch;
mod audit;
mod automation_contract;
mod decision_engine;
mod decision_queue;
mod task_graph;
mod workspace_activity;
mod workspace_attention;
mod workspace_continuity;
mod workspace_environment;
mod workspace_composition;
mod workspace_purpose;
mod workspace_evolution;
mod workspace_recommendation;
mod workspace_operating_state;
mod workspace_pattern;
mod workspace_adaptation;
mod workspace_readiness;
mod workspace_session;
mod workspace_experience;
mod workspace_work_context;
mod workspace_navigation;
mod workspace_milestone;
mod workspace_scope;
mod trigger_evaluator;
mod configuration;
mod context;
mod database;
mod desktop_window;
mod discovery;
mod execution_cancellation;
mod execution_context;
mod execution_guard;
mod execution_outcome;
mod execution_reconciliation;
mod graph;
mod layout;
mod intent_execution;
mod observation;
mod permission_approval;
mod projection;
mod registry;
mod suggestion;
mod suggestion_intent;
mod suggestion_lifecycle;
mod widget;
mod workspace;
mod workspace_intelligence;
mod workspace_intent;
mod zone;

pub use action_catalog::ActionCatalogService;
pub(crate) use ai_assistant::{AiAssistantService, AssistantWorkflowStore};
pub(crate) use ai_evaluation::AiEvaluationService;
pub(crate) use ai_memory::AiMemoryService;
pub(crate) use ai_model_provider::{
    DeterministicModelProvider, EchoModelProvider, ModelProviderRegistry, ModelProviderService,
    UnavailableModelProvider,
};
pub(crate) use ai_orchestration::{AiOrchestrationService, OrchestratedPlanStore};
pub(crate) use ai_personalization::AiPersonalizationService;
pub(crate) use ai_participation::AiParticipationService;
pub(crate) use ai_planning::AiPlanningService;
pub use analytics::WorkspaceAnalyticsService;
pub use application::ApplicationService;
pub(crate) use application_launch::ApplicationLaunchService;
pub use audit::AuditService;
pub(crate) use automation_contract::AutomationContractService;
pub use configuration::ConfigurationService;
pub(crate) use decision_engine::DecisionEngineService;
pub(crate) use decision_queue::DecisionQueueService;
pub(crate) use task_graph::TaskGraphService;
pub(crate) use trigger_evaluator::{list_rejection_summaries, TriggerEvaluatorService};
pub(crate) use workspace_activity::WorkspaceActivityGraphService;
pub(crate) use workspace_attention::WorkspaceAttentionService;
pub(crate) use workspace_continuity::WorkspaceContinuityService;
pub(crate) use workspace_environment::WorkspaceEnvironmentService;
pub(crate) use workspace_composition::WorkspaceCompositionService;
pub(crate) use workspace_purpose::WorkspacePurposeService;
pub(crate) use workspace_evolution::WorkspaceEvolutionService;
pub(crate) use workspace_recommendation::WorkspaceRecommendationEngineService;
pub(crate) use workspace_operating_state::WorkspaceOperatingStateService;
pub(crate) use workspace_pattern::WorkspacePatternService;
pub(crate) use workspace_adaptation::WorkspaceAdaptationService;
pub(crate) use workspace_readiness::WorkspaceReadinessService;
pub(crate) use workspace_session::WorkspaceSessionService;
pub(crate) use workspace_experience::WorkspaceExperienceService;
pub(crate) use workspace_work_context::WorkspaceWorkContextService;
pub(crate) use workspace_navigation::WorkspaceNavigationService;
pub(crate) use workspace_milestone::WorkspaceMilestoneService;
pub(crate) use workspace_scope::{approval_belongs_to_workspace, plan_belongs_to_workspace};
pub use context::WorkspaceContextService;
pub use database::DatabaseServiceHandle;
pub use desktop_window::DesktopWindowService;
pub use discovery::CapabilityResolver;
pub use execution_cancellation::ExecutionCancellationService;
pub use execution_context::ExecutionContextService;
pub use execution_guard::ExecutionGuardService;
pub use execution_outcome::ExecutionOutcomeService;
pub use execution_reconciliation::ExecutionReconciliationService;
pub use graph::GraphService;
pub use layout::LayoutService;
pub use intent_execution::GovernedIntentExecutionService;
pub use observation::ObservationService;
pub(crate) use permission_approval::PermissionApprovalService;
pub use projection::WorkspaceProjectionService;
pub use registry::{RegisteredService, ServiceRegistry, ServiceStatus};
pub use suggestion::SuggestionService;
pub use suggestion_intent::SuggestionIntentService;
pub use suggestion_lifecycle::SuggestionLifecycleService;
pub use widget::WidgetService;
pub use workspace::WorkspaceService;
pub(crate) use workspace_intelligence::WorkspaceIntelligenceService;
pub(crate) use workspace_intent::WorkspaceIntentService;
pub use zone::ZoneService;
