export {
  ADAPTATION_STORAGE_KEY,
  ADAPTATION_CHANGED_EVENT,
  activateAdaptation,
  buildAdaptationFromLineage,
  clearAdaptationStore,
  deactivateAdaptation,
  defaultAdaptationStore,
  getAdaptation,
  identityPresentation,
  listAdaptations,
  persistAdaptation,
  presentationToShellStyle,
  resolvePresentationConfiguration,
  rollbackAdaptation,
  upsertValidatedAdaptation,
  validateAdaptationEvidence,
  verifyAdaptationLineage,
} from "./workspaceAdaptation";
export type {
  WorkspaceAdaptation,
  PresentationConfiguration,
  ResolvedPresentation,
  AdaptationScope,
  AdaptationRolloutState,
  AdaptationTargetComponent,
  AdaptationValidationContract,
  AdaptationLineageContext,
  AdaptationLineageError,
  AdaptationStabilityReport,
  LongitudinalAdaptationRecord,
  RollbackCriterion,
} from "./workspaceAdaptation";
export { useResolvedPresentation } from "./useResolvedPresentation";
export {
  ADAPTATION_EXPERIMENT_SPECS,
  EXPERIMENT_STORAGE_KEY,
  clearExperimentStore,
  experimentRollbackReady,
  getExperimentSummary,
  listExperimentResults,
  materializeExperimentLineage,
  runAdaptationExperiments,
  selectEligibleProposals,
  selectExperimentSpecs,
  toggleAdaptationExperiment,
} from "./adaptationExperiments";
export type {
  AdaptationExperimentResult,
  AdaptationExperimentSpec,
  ExperimentRunSummary,
  ExperimentStatus,
  RolloutDisposition,
} from "./adaptationExperiments";
export {
  LONGITUDINAL_MIN_OBSERVATIONS,
  LONGITUDINAL_STABILITY_THRESHOLD,
  LONGITUDINAL_MAX_UNRESOLVED_REGRESSIONS,
  analyzeAdaptationStability,
  appendLongitudinalObservation,
  buildLongitudinalRecord,
  getLongitudinalRecord,
  getStabilityReport,
  isRolloutReady,
  listLongitudinalRecords,
  listRolloutCandidates,
  listStabilityReports,
  promoteToRolloutCandidate,
  runLongitudinalValidation,
} from "./longitudinalAdaptation";
export type { LongitudinalTransitionError } from "./longitudinalAdaptation";
