export {
  ADAPTATION_STORAGE_KEY,
  ADAPTATION_CHANGED_EVENT,
  activateAdaptation,
  buildAdaptationFromLineage,
  clearAdaptationStore,
  deactivateAdaptation,
  defaultAdaptationStore,
  getAdaptation,
  identityPresentation,
  listAdaptations,
  persistAdaptation,
  presentationToShellStyle,
  resolvePresentationConfiguration,
  rollbackAdaptation,
  upsertValidatedAdaptation,
  validateAdaptationEvidence,
  verifyAdaptationLineage,
} from "./workspaceAdaptation";
export type {
  WorkspaceAdaptation,
  PresentationConfiguration,
  ResolvedPresentation,
  AdaptationScope,
  AdaptationRolloutState,
  AdaptationTargetComponent,
  AdaptationValidationContract,
  AdaptationLineageContext,
  AdaptationLineageError,
  RollbackCriterion,
} from "./workspaceAdaptation";
export { useResolvedPresentation } from "./useResolvedPresentation";
export {
  ADAPTATION_EXPERIMENT_SPECS,
  EXPERIMENT_STORAGE_KEY,
  clearExperimentStore,
  experimentRollbackReady,
  getExperimentSummary,
  listExperimentResults,
  materializeExperimentLineage,
  rollbackExperimentAdaptation,
  runAdaptationExperiments,
  selectEligibleProposals,
  selectExperimentSpecs,
  toggleAdaptationExperiment,
} from "./adaptationExperiments";
export type {
  AdaptationExperimentResult,
  AdaptationExperimentSpec,
  ExperimentRunSummary,
  ExperimentStatus,
  RolloutDisposition,
} from "./adaptationExperiments";
