mod ai_memory;
mod application;
mod audit;
mod automation_contract;
mod automation_trigger;
#[cfg(test)]
mod boundary_tests;
mod cognitive_agent_cast;
mod cognitive_autonomy;
mod cognitive_graph;
mod cognitive_model;
mod cognitive_orchestration;
mod decision_engine;
mod decision_queue;
mod execution_lifecycle;
mod graph;
mod historical_reconstruction;
mod layout;
mod learning_adaptation;
mod observation;
mod permission_approval;
mod policy_governance;
mod reasoning_memory;
mod recommendation_lifecycle;
mod task_graph;
mod temporal_intelligence;
mod user_preference;
mod widget;
mod workspace;
mod workspace_assistant_context;
mod workspace_assistant_explanation;
mod workspace_assistant_interaction;
mod workspace_assistant_retrieval;
mod workspace_assistant_surface;
mod workspace_contextual_understanding;
mod workspace_cross_intelligence;
mod workspace_decision_support;
mod workspace_evidence_completeness;
mod workspace_evidence_consistency;
mod workspace_evidence_coverage;
mod workspace_evidence_dependency;
mod workspace_evidence_freshness;
mod workspace_evidence_navigation;
mod workspace_evidence_reliability;
mod workspace_evidence_trace;
mod workspace_explanation;
mod workspace_insight_coordination;
mod workspace_intelligence_hub;
mod workspace_intent;
mod workspace_knowledge_integration;
mod workspace_knowledge_synthesis;
mod workspace_planning;
mod workspace_profile;
mod workspace_semantic_query;
mod workspace_state_envelope;
mod zone;

pub use ai_memory::AiMemoryRepository;
pub use application::ApplicationRepository;
pub use audit::AuditRepository;
pub use automation_contract::AutomationContractRepository;
pub use automation_trigger::AutomationTriggerRepository;
pub use cognitive_agent_cast::CognitiveAgentCastRepository;
pub use cognitive_autonomy::CognitiveAutonomyRepository;
pub use cognitive_graph::CognitiveGraphRepository;
pub use cognitive_model::CognitiveModelRepository;
pub use cognitive_orchestration::CognitiveOrchestrationRepository;
pub use decision_engine::DecisionEngineRepository;
pub use decision_queue::DecisionQueueRepository;
pub use execution_lifecycle::ExecutionLifecycleRepository;
pub use graph::GraphRepository;
pub use historical_reconstruction::HistoricalReconstructionRepository;
pub use layout::LayoutRepository;
pub use learning_adaptation::LearningAdaptationRepository;
pub use observation::{
    ObservationMonitorRepository, ObservationPassRepository, ObservationWindowIdentityRepository,
    ObservationWindowRepository,
};
pub use permission_approval::PermissionApprovalRepository;
pub use policy_governance::PolicyGovernanceRepository;
pub use reasoning_memory::ReasoningMemoryRepository;
pub use recommendation_lifecycle::RecommendationLifecycleRepository;
pub use task_graph::TaskGraphRepository;
pub use temporal_intelligence::TemporalIntelligenceRepository;
pub use user_preference::UserPreferenceRepository;
pub use widget::WidgetRepository;
pub use workspace::WorkspaceRepository;
pub use workspace_assistant_context::WorkspaceAssistantContextRepository;
pub use workspace_assistant_explanation::WorkspaceAssistantExplanationRepository;
pub use workspace_assistant_interaction::WorkspaceAssistantInteractionRepository;
pub use workspace_assistant_retrieval::WorkspaceAssistantRetrievalRepository;
pub use workspace_assistant_surface::WorkspaceAssistantSurfaceRepository;
pub use workspace_contextual_understanding::WorkspaceContextualUnderstandingRepository;
pub use workspace_cross_intelligence::WorkspaceCrossIntelligenceRepository;
pub use workspace_decision_support::WorkspaceDecisionSupportRepository;
pub use workspace_evidence_completeness::WorkspaceEvidenceCompletenessRepository;
pub use workspace_evidence_consistency::WorkspaceEvidenceConsistencyRepository;
pub use workspace_evidence_coverage::WorkspaceEvidenceCoverageRepository;
pub use workspace_evidence_dependency::WorkspaceEvidenceDependencyRepository;
pub use workspace_evidence_freshness::WorkspaceEvidenceFreshnessRepository;
pub use workspace_evidence_navigation::WorkspaceEvidenceNavigationRepository;
pub use workspace_evidence_reliability::WorkspaceEvidenceReliabilityRepository;
pub use workspace_evidence_trace::WorkspaceEvidenceTraceRepository;
pub use workspace_explanation::WorkspaceExplanationRepository;
pub use workspace_insight_coordination::InsightCoordinationRepository;
pub use workspace_intelligence_hub::WorkspaceIntelligenceHubRepository;
pub use workspace_intent::WorkspaceIntentRepository;
pub use workspace_knowledge_integration::WorkspaceKnowledgeIntegrationRepository;
pub use workspace_knowledge_synthesis::WorkspaceKnowledgeSynthesisRepository;
pub use workspace_planning::WorkspacePlanningRepository;
pub use workspace_profile::WorkspaceProfileRepository;
pub use workspace_semantic_query::WorkspaceSemanticQueryRepository;
pub use workspace_state_envelope::WorkspaceStateEnvelopeRepository;
pub use zone::ZoneRepository;
